### PR TITLE
Add mocked builtin methods to fix copy and pickle for GenieConf* classes.

### PR DESCRIPTION
**Pull request by atronchi**
Fixes https://bugs.python.org/issue19364

Tests:
```
In [2]: import pygenie

In [3]: g = pygenie.conf.GenieConf()

In [4]: g.__copy__()
Out[4]: GenieConf()

In [5]: g.__deepcopy__()
Out[5]: GenieConf()
```

### CODE REVIEW

**Comment by stephen-mw** [comment]
Can you help me understand your use-case better in regards to issue19364? Are you making discrete copies of the GenieConf() module for individualized authentication objects?

Personally I would prefer not to introduce or redefine built-ins in this scenario because the underlying fix is in-place for Genie3 and there may be "easy" work-arounds. If @irontable disagrees then we can go on to discuss the implementation.

**Comment by atronchi** [comment]
The below errors occur using these classes as imported from current versions of kragle.djinn.SparkJob, so no underlying fix appears to be in-place for Genie3 on kragle unless kragle is using an old unfixed version of pygenie. What fix are you referring to?

Using deepcopy on instantiated kragle.djinn.SparkJob classes results in errors due to the absence of these methods as shown below:

- [A simple repro](https://files.slack.com/files-pri/T029N2L97-F7ME9GZN2/Errors_copying_instantiated_kragle_djinn__Job_classes.txt)
- [An example of this error manifested when airflow tried to pickle a DAG or build a sub-DAG based on kragle.djinn.*Job classes](https://files.slack.com/files-pri/T029N2L97-F7ML4UG3Z/19364_type_errors_with_airflow_backfills_.txt)

**Comment by atronchi** [comment]
The second example I showed above does not actually result from issues with copy, but with pickling. I've updated the PR to also fix pickling issues. With these changes, it is possible to pickle instantiated *Job classes.

**Comment by stephen-mw** [comment]
Hi Alex. For the moment the Kragle owner (@irontable) is out of office. My recommendation is that we want for him to return and we discuss further. He returns on the 30th.

**Comment by atronchi** [comment]
Sounds good! Talk to you next week.

**Comment by atronchi** [comment]
Ping @irontable and @stephen-mw ?

**Comment by atronchi** [comment]
#weeklyping!
https://www.youtube.com/watch?v=aHN6AViJAvI

**Pull request merged**
